### ISSUE TITLE
To improve the About Dialog

### ISSUE THREAD

**Issue by PauloSSAragao** [mapuiexts/React-OlExt#2]
The about dialog has to be improved with the following items:
a) link to documentation
b) link to source code
c) link to live demos section in the documentation
c) License
d) AboutButton should accept and additional property. So the user can provide information about his own application 
          `<AboutWnd><p>my application is... </p></AboutButton>`
         
e) To change automatically the color for the name "React-Olext" if user customize the theme
          See the application basic-app-with-custom-theme in the section "Live Demos"

**Comment by cristianoveiga** [comment]
@PauloSSAragao I sent you a PR for this issue. The only thing missing now is the item e).
